// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYlPdUrE5OtLfzITs5P2KYrr5OsI5YKYo',
    appId: '1:642886306879:web:4384af1af0713ede093c8a',
    messagingSenderId: '642886306879',
    projectId: 'fitlife-d54e5',
    authDomain: 'fitlife-d54e5.firebaseapp.com',
    storageBucket: 'fitlife-d54e5.appspot.com',
    measurementId: 'G-JM9FCP6Y63',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAl5S4m7NyAhRkCH_TR4f2zfGrDLw_M2OY',
    appId: '1:642886306879:android:7f62b50663e6a04a093c8a',
    messagingSenderId: '642886306879',
    projectId: 'fitlife-d54e5',
    storageBucket: 'fitlife-d54e5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGFyc-gM5V48SuRhZ2dkpu5IVVNUWexcc',
    appId: '1:642886306879:ios:d4a540bd048e7771093c8a',
    messagingSenderId: '642886306879',
    projectId: 'fitlife-d54e5',
    storageBucket: 'fitlife-d54e5.appspot.com',
    iosBundleId: 'com.example.flutterBaseCleanArchitecture',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGFyc-gM5V48SuRhZ2dkpu5IVVNUWexcc',
    appId: '1:642886306879:ios:189cd23c372e4088093c8a',
    messagingSenderId: '642886306879',
    projectId: 'fitlife-d54e5',
    storageBucket: 'fitlife-d54e5.appspot.com',
    iosBundleId: 'com.example.flutterBaseCleanArchitecture.RunnerTests',
  );
}
